"""add foreign keys to TransportPets

Revision ID: 12ea5f1b7710
Revises: 3e4d4ab3624a
Create Date: 2024-03-17 23:44:01.141442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ea5f1b7710'
down_revision = '3e4d4ab3624a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pet_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sending_org_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('receiving_org_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_transport_pets_sending_org_id_organizations'), 'organizations', ['sending_org_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_transport_pets_pet_id_pets'), 'pets', ['pet_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_transport_pets_transport_id_transports'), 'transports', ['transport_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_transport_pets_receiving_org_id_organizations'), 'organizations', ['receiving_org_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_pets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transport_pets_receiving_org_id_organizations'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transport_pets_transport_id_transports'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transport_pets_pet_id_pets'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transport_pets_sending_org_id_organizations'), type_='foreignkey')
        batch_op.drop_column('receiving_org_id')
        batch_op.drop_column('sending_org_id')
        batch_op.drop_column('pet_id')
        batch_op.drop_column('transport_id')

    # ### end Alembic commands ###
