"""add TransportPets and TransportOrganizations

Revision ID: 2e3be944cc3d
Revises: 70cc6a9348f1
Create Date: 2024-03-16 20:57:11.594161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3be944cc3d'
down_revision = '70cc6a9348f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_sending', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport_pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transport_pets')
    op.drop_table('transport_organizations')
    # ### end Alembic commands ###
