"""rename type to species

Revision ID: 3e4d4ab3624a
Revises: 3712575a9538
Create Date: 2024-03-17 22:46:19.471224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4d4ab3624a'
down_revision = '3712575a9538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pets', 'type',  new_column_name='species')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pets', 'type',  new_column_name='type')

    # ### end Alembic commands ###
