"""add receiving_org to Pet

Revision ID: 7ecaadef62a6
Revises: d4672c823f0a
Create Date: 2024-04-11 12:44:01.115931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ecaadef62a6'
down_revision = 'd4672c823f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiving_org_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_pets_receiving_org_id_organizations'), 'organizations', ['receiving_org_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pets_receiving_org_id_organizations'), type_='foreignkey')
        batch_op.drop_column('receiving_org_id')

    # ### end Alembic commands ###
