"""add foreign keys to TransportOrganization

Revision ID: a67a22068969
Revises: 743e685a87d0
Create Date: 2024-03-18 01:32:05.992375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67a22068969'
down_revision = '743e685a87d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_transport_organizations_transport_id_transports'), 'transports', ['transport_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_transport_organizations_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_organizations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transport_organizations_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transport_organizations_transport_id_transports'), type_='foreignkey')
        batch_op.drop_column('organization_id')
        batch_op.drop_column('transport_id')
