"""drop receiving org

Revision ID: d4672c823f0a
Revises: a67a22068969
Create Date: 2024-04-10 19:02:24.308130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4672c823f0a'
down_revision = 'a67a22068969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_pets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transport_pets_receiving_org_id_organizations', type_='foreignkey')
        batch_op.drop_column('receiving_org_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiving_org_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_transport_pets_receiving_org_id_organizations', 'organizations', ['receiving_org_id'], ['id'])

    # ### end Alembic commands ###
