"""add flight_risk to Pet

Revision ID: de0e69164c77
Revises: d07f642f0773
Create Date: 2024-03-16 20:22:39.139567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0e69164c77'
down_revision = 'd07f642f0773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_risk', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('flight_risk')

    # ### end Alembic commands ###
